### ISSUE TITLE
Missing backslash for sqrt

### ISSUE THREAD

**Issue by thomasahle** [VoLuong/Begin-Latex-in-minutes#1]
The amsmath example writes sqrt where \sqrt was perhaps meant?

**Comment by luong-komorebi** [comment]
I am very sorry! It was my mistake. Thank you for making this issue 😄 The latest commit fixed that.

**Comment by thomasahle** [comment]
Great! You should probably also use curly brackets {x} rather than (x), since otherwise the sqrt sign is only around the first "("! :-D
Thanks for the great document!

**Comment by luong-komorebi** [comment]
Oh no that was another mistake of mine. So sorry because i dont usually use latex for math. As a compensation, I have just done some research on math latex and added a more interesting example. 
Again, thank you 👍  @thomasahle

**Comment by thomasahle** [comment]
Very cool! And I'm just happy to assist :-)
