### ISSUE TITLE
PDF Viewer on Windows matter

### ISSUE THREAD

**Issue by maxnoe** [VoLuong/Begin-Latex-in-minutes#10]
Most PDF viewers on Windows, especially Acrobat readers block writing to the pdf when it is opened. This leads to an error if you compile again.

There are some viewers which don't block and also update if the pdf was updatet, e. g. Sumatra PDF

**Comment by vermiculus** [comment]
Evince is also such a reader, as is any browser (usually).

**Comment by maxnoe** [comment]
Evince on windows is dead.

**Comment by luong-komorebi** [comment]
Wow did not see that problem coming . Thank you. I added a small warning for the user.

**Comment by vermiculus** [comment]
@MaxNoe Is it really? :slightly_frowning_face: I haven't been doing serious work on Windows for quite some time. I'm sorry to hear the project's dead now.

**Comment by maxnoe** [comment]
@vermiculus

Pretty much, last Windows release is 2.32 from 2010.
