### ISSUE TITLE
Suggestion: look at minted for code listings

### ISSUE THREAD

**Issue by mbaz** [VoLuong/Begin-Latex-in-minutes#12]
IMHO minted is much better than lstlistings for code: https://www.ctan.org/tex-archive/macros/latex/contrib/minted/

**Comment by luong-komorebi** [comment]
Thank you for your suggestion. I will try it then update the guide if possible. Until then I will leave this issue open ;)

**Comment by vermiculus** [comment]
As a general rule, packages that use external tools (gnuplot is another example) are generally faster and easier to use, but the initial setup can be intimidating.

There are sometimes integration problems as well (as is the case with gnuplot and font integration).

Minted leverages the Python package Pygments to do its syntax analysis and highlighting. Believe it or not, LaTeX is _not_ cut out for this job (even though the `listings` package is impressive, stable, and time-tested).
