### ISSUE TITLE
What should we do about compile steps?

### ISSUE THREAD

**Issue by vermiculus** [VoLuong/Begin-Latex-in-minutes#22]
Many tools require special build steps (eg. #12 or anything that uses bibliographies), but there is no mention of this in the document. In [my own examples](https://github.com/vermiculus/texample/tree/master/latex/biblatex), I use [cereda/arara](https://github.com/cereda/arara) to explicitly define how to compile each example in the repository. I'd suggest using that since the compilation steps can be inlined with the examples themselves.

**Comment by luong-komorebi** [comment]
> bibliographies[...]but there is no mention of this in the document .  

 I admitted that I did skip bibliography and some complicated things to keep this easy and beginner-friendly. And I have never used an automation tool like [cereda/arara](https://github.com/cereda/arara) before.
