### ISSUE TITLE
More committers are needed

### ISSUE THREAD

**Issue by JunoJunho** [VoLuong/Begin-Latex-in-minutes#27]
I think the author may not handle all the issues and PRs, so @VoLuong needs 2-3 mans to manage this project because he is a student as we are.

**Comment by luong-komorebi** [comment]
@JunoJunho  I am sorry to hear so. I am very active in this repo. Unfortunately, my laptop has just broken last night. I did see your pull request and it got some conflicts that I really need my laptop to solve. However, the only thing I am using ( even to reply to you here ) is my bare phone. Please be keen, I am not dropping this.

**Comment by luong-komorebi** [comment]
Right before you, #20 has received a lot of reviews but the author of that PR just didn't fix them, so I dont merge it.

**Comment by JunoJunho** [comment]
Oh, I didn't notice about it. I'm sorry to hear that. Let's do it together :) I try to make more contributions.
