### ISSUE TITLE
Malfunctioned links found on line 432

### ISSUE THREAD

**Issue by ghost** [VoLuong/Begin-Latex-in-minutes#39]
The URLs `https://s14.postimg.org/deg0kqhu9/multi_file.png` and `https://postimg.org/image/hnkqmwl3h/` give Server Not Found error.

**Comment by luong-komorebi** [comment]
Thank you for informing me @konquetty . Somehow this issue did not fire any notification to me, but your closing it does. I am sorry. I took action removing that link and moved the image to Github.

**Comment by ghost** [comment]
No need to apologize. Glad it's fixed.
