### ISSUE TITLE
Identical language selection block for all translations

### ISSUE THREAD

**Issue by i-ky** [VoLuong/Begin-Latex-in-minutes#41]
Currently the part that talks about available translations looks very different across `Translation:*` files. Moreover, some of them are outdated. And finally, it does not make much sense to say that there is Spanish translation available _in French_. :)

Would be nice to make language selection blocks identical. And every language should be written "in itself". I think it could look like [this](https://ds6br8f5qp1u2.cloudfront.net/blog/wp-content/uploads/2016/08/language-switcher-footer.png).

If you like the idea I can take care of pull request.

**Comment by luong-komorebi** [comment]
I really like the idea. Thanks for your opinion. I may do it myself but if you feel like dealing with it, I will leave the stage for you ;)

**Comment by i-ky** [comment]
I finally did it! Sorry that it took so long.

**Comment by luong-komorebi** [comment]
@i-ky no problem. It really doesnt matter that much ;)
