### ISSUE TITLE
Invalid file name in windows

### ISSUE THREAD

**Issue by inkydragon** [VoLuong/Begin-Latex-in-minutes#54]
In windows, filename cannot contain colon (`:`).
 
> > Short and long file names must not contain the following characters:
> 
> slash (`/`) or (`\`)
> question mark (`?`)
> vertical bar (`|`)
> right angle bracket (`>`)
> left angle bracket (`<`)
> colon (`:`)
> 
> - [Filename - Windows applications | Microsoft Docs](https://docs.microsoft.com/en-us/windows/desktop/msi/filename)

When I use github desktop for windows or git in cmd or powershell, I only got a `readme.md` and a 0 KB `Translation` file.

![image](https://user-images.githubusercontent.com/5158738/57420829-e27d2500-723b-11e9-97cc-e41944dba3b6.png)

and If I use git in wsl, all the `:` in filename are replace to `` automatically.

![image](https://user-images.githubusercontent.com/5158738/57421074-ebbac180-723c-11e9-86ef-1cfffdedc9ed.png)

**Comment by luong-komorebi** [comment]
Thanks for your report. Sorry I wasn't using Windows when I wrote this guide. I ll try to change the filename ASAP ;)

**Comment by luong-komorebi** [comment]
Hi there, can you help review https://github.com/luong-komorebi/Begin-Latex-in-minutes/pull/56 ?
