### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by Kastakin** [VoLuong/Begin-Latex-in-minutes#58]
There's a broken link to an image present in the [Multiple files in LaTeX section](https://github.com/luong-komorebi/Begin-Latex-in-minutes#multiple-files-in-latex)

clicking the [link](https://camo.githubusercontent.com/e4d46edfad527c4c9be54cf8f1725c2fc52039d6/68747470733a2f2f7331342e706f7374696d672e6f72672f646567306b716875392f6d756c74695f66696c652e706e67) result in a "Cannot proxy the given URL" error

**Comment by luong-komorebi** [comment]
Thanks for the bug report. I dont know why but the old image is hosted on Github so that s not in my control. Just updated it
