### ISSUE TITLE
Obscenity

### ISSUE THREAD

**Issue by zh217** [VoLuong/Begin-Latex-in-minutes#7]
Naming your file "shit.tex" isn't very helpful for encouraging beginners ...

See the first screenshot

https://camo.githubusercontent.com/c3da4b68c38084a999bf10b9a984251bbc9ff6d7/687474703a2f2f692e696d6775722e636f6d2f584a786f5879492e6a7067

**Comment by luong-komorebi** [comment]
Sorry! I will try to fix  this soon. So sorry I was high when going into LaTex....

**Comment by luong-komorebi** [comment]
It is now modified. Thank you
