### ISSUE TITLE
On LaTeX compilers and Unicode

### ISSUE THREAD

**Issue by Kwpolska** [VoLuong/Begin-Latex-in-minutes#9]
> Some languages won't work right out of the box. You will need to include some packages for the font to render. Also, you will learn about "packages" later. For example:

``` tex
\documentclass[a4paper]{article}

\usepackage[T5]{fontenc}
\usepackage[utf8]{inputenc}

\begin{document}

Xin chào thế giới. This is Hellow World in Vietnamese.

\end{document}
```

It looks like you’re still living in the 90s where Unicode support was neglected. You see, two projects have solved this problem: XeTeX and LuaTeX. Those are two compilers with Unicode support.

``` tex
\documentclass[a4paper]{article}
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainfont[]{Baskerville} % any TTF or OTF fonts from my system will do
\begin{document}
Xin chào thế giới. This is Hello World in Vietnamese.

The quick brown fox jumps over the lazy dog.

Pchnąć w tę łódź jeża lub ośm skrzyń fig.

Quiere la boca exhausta vid, kiwi, piña y fugaz jamón.

Vogt Nyx: »Büß du ja zwölf Qirsch, Kämpe!«

Любя, съешь щипцы, — вздохнёт мэр, — кайф жгуч.
\end{document}
```

![International TeX with Baskerville](https://cloud.githubusercontent.com/assets/327323/19838397/be5097cc-9ece-11e6-8f38-35cec87f10c5.png)

If I don’t set any font (remove line with comment), the font will default to Latin Modern, which is a reworking of Computer Modern with support for many Latin diacritic characters. The Russian part fails.

![International-ish TeX with Latin Modern](https://cloud.githubusercontent.com/assets/327323/19838410/e3150b56-9ece-11e6-9070-2cace75c96e5.png)

In TeXstudio (and probably TeXMaker): change Build → Default Compiler in the settings. I’m using LuaLaTeX.

**Comment by luong-komorebi** [comment]
> It looks like you’re still living in the 90s where Unicode support was neglected. 

I was sharing what I was taught 😃 It may be limited so yeah, maybe I am a little outdated. I will try your suggestion and update the guide ASAP. Thank you for your suggestions 👍 

@Kwpolska  Can you do a pull request adding LaTeX compilers / editors that you favor in the Additional Tools section?
